### ISSUE TITLE
50k limit on ManifestWork not enough to define larger/more complex add-ons

### ISSUE THREAD

**Issue by dangorst1066** [open-cluster-management-io/addon-framework#116]
The current add-on framework creates a single ManifestWork that includes **all** the resources the add on requires to run in the managed clusters.

There is a 50k limit on the size of a ManifestWork resource [set here](https://github.com/open-cluster-management-io/work/blob/6ccdd098811e97e88e71b65dcaa55cfed1e8b6b0/pkg/webhook/manifestwork_webhook.go#L19-L20) which creates a problem when attempting to deploy more complex add ons , that define many resources. A single CRDs can easily exceed 50k on it's own - for example `kustomizations.kustomize.toolkit.fluxcd.io` is 60k. 

Suggestion is to make the limit on a single ManifestWork configurable (primarily for large CRDs or ConfigMaps)  _AND_ update the addon controller to create a ManifestWork per resource (or similar) rather than bundling them all together into a single ManifestWork.

**Comment by qiujian16** [comment]
/assign @qiujian16 
/kind bug

cc @zhiweiyin318

**Comment by qiujian16** [comment]
fixed by https://github.com/open-cluster-management-io/addon-framework/pull/122
