### ISSUE TITLE
`AddOnDeloyment` is missing a `p`

### ISSUE THREAD

**Issue by dhaiducek** [open-cluster-management-io/addon-framework#134]
`AddOnDeloyment` --> `AddOnDeployment`

Affects:
- `GetAddOnDeloymentConfigValues`
- `NewAddOnDeloymentConfigGetter`

Not sure the best route for handling this, but a deprecation note and having the misspelled function point to the new function might work? It's a minor thing, but I think fixing it is important.

**Comment by zhiweiyin318** [comment]
fixed.
/close
