### ISSUE TITLE
RFE: UpdateStrategy in AgentAddonOptions

### ISSUE THREAD

**Issue by fgiloux** [open-cluster-management-io/addon-framework#173]
Today it is not possible to specify in [AgentAddonOptions](https://github.com/open-cluster-management-io/addon-framework/blob/main/pkg/agent/inteface.go#L42-L73) the [UpdateStrategy](https://github.com/open-cluster-management-io/api/blob/v0.10.1/work/v1/types.go#L97). 
It would be useful to specify that "create only" or  "server side apply" is to be used for some manifests containing configuration data so that regular changes made by users do not get overwritten by an update of the resource pushed by the addon as described here:
https://open-cluster-management.io/concepts/manifestwork/#resource-race-and-adoption

If you find this request meaningful I am happy to try to contribute the implementation.

**Comment by qiujian16** [comment]
yes, I think it is pretty useful
cc @zhiweiyin318

**Comment by fgiloux** [comment]
Thanks for the feedback. I will look at that next week if time allows.
