### ISSUE TITLE
Add support to configure helm-agent-addon namespace.

### ISSUE THREAD

**Issue by Imtiaz246** [open-cluster-management-io/addon-framework#217]
**Problem Statement:**
- We are creating a `helm-agent-addon` using the [installStrategy feature](https://github.com/open-cluster-management-io/api/blob/bab1208e6889582db98e95e8210680c5ef843a5a/addon/v1alpha1/types_clustermanagementaddon.go#L61) defined in the `ClusterManagementAddon` API. Currently we can't configure the namespace dynamically as per the [ocm:issues:298](https://github.com/open-cluster-management-io/ocm/issues/298)  describes. In our use case, we need the ability to configure the namespace for the helm-agent-addon dynamically. 
- Additionally, we want to leverage helm chart built-in values such as `{{ Release.Namespace }}` and `{{ Release.Name }}` to set the values of the helm-agent-addon.

**Proposed Solution:**
- We propose adding a feature/enhancement that allows for the dynamic configuration of the `helm-agent-addon` namespace. This would enable users to specify the namespace at build time through some configuration parameters.

**Use Case Example:**
- For example, in our use case, we want to set the `helm-agent-addon` namespace using the helm chart built-in value `{{ Release.Namespace }}` which would ensure consistency with the parent Helm release.

**Comment by zhujian7** [comment]
@Imtiaz246 thanks for reporting this

> we can't configure the namespace dynamically as per the https://github.com/open-cluster-management-io/ocm/issues/298 describes.

PR https://github.com/open-cluster-management-io/addon-framework/pull/218 is trying to fix this.


> additionally, we want to leverage helm chart built-in values such as {{ Release.Namespace }} and {{ Release.Name }}

there are [3 helm built-in values](https://open-cluster-management.io/developer-guides/addon/#values-definition) are supported, fortunately, `{{ Release.Namespace }}` and `{{ Release.Name }}` are included.

**Comment by zhujian7** [comment]
@Imtiaz246 I submitted [a PR to support configuring the namespace for the helm addons](https://github.com/open-cluster-management-io/addon-framework/pull/218), if you want you can try it with the latest addon-framework, example [here](https://github.com/open-cluster-management-io/addon-framework/blob/main/cmd/example/helloworld_helm/main.go#L130-L135)

**Comment by Imtiaz246** [comment]
Great @zhujian7. Thank you for your quick response. Things are working as expected now.

**Comment by tamalsaha** [comment]
@zhujian7 , I think there is still one thing left to fix

https://github.com/open-cluster-management-io/addon-framework/blob/674dd8271a0870560a39829e189f56d13d7a6dd5/pkg/addonmanager/controllers/addoninstall/controller.go#L97-L113

`addon.GetAgentAddonOptions().InstallStrategy.InstallNamespace` is configured correctly

**Comment by tamalsaha** [comment]
There is also one more issue here. The `ManagedClusterAddon` crd defaults `installNamespace` to `open-cluster-management-agent-addon`.

https://github.com/open-cluster-management-io/api/blob/658739714f84467fa4e057c24d594fd6d416bed9/addon/v1alpha1/types_managedclusteraddon.go#L39

This causes problem because it does not take the correct installNamespace from the `ClusterManagementAddon`.
https://github.com/open-cluster-management-io/ocm/blob/8a4c834ebf0f3c71ab9209572fb0b11cc942f5d5/pkg/addon/controllers/addonmanagement/addon_install_reconciler.go#L72

**Comment by zhujian7** [comment]
@tamalsaha we are going to [deprecate the managedclusteraddon.spec.instllNamespace](https://github.com/open-cluster-management-io/ocm/issues/298), if you want to make the ns configurable, I suggest you use the [AgentInstallNamespace func](https://github.com/open-cluster-management-io/addon-framework/blob/5c0a0855a65e3ce3c895ef031c973887a5af2a6a/pkg/agent/inteface.go#L121) to fully control the namespace value, for example, you can implement this func to read the value from the API [addondeploymentconfig.spec.agentInstallNamespace](https://github.com/open-cluster-management-io/api/blob/6ec504f69bfb79bac5c8e3cc6e1f9ea744713404/addon/v1alpha1/types_addondeploymentconfig.go#L59), then any value changed in the field `addondeploymentconfig.spec.agentInstallNamespace` will be reflected on where the addon agent is installed.
