### ISSUE TITLE
helm addon: GetSpecHash unable to handle  ConfigMap and Secret resources

### ISSUE THREAD

**Issue by JoaoBraveCoding** [open-cluster-management-io/addon-framework#237]
**Describe the bug**

As far as I understand the function `GetSpecHash` is used to generate a hash with the `Spec` content of a k8s resource. This hash is stored in the status of ManagedClusterAddOn and used by the framework to know if the current state of ManifestWorks is up to date. The problem is that when we use as config resources k8s resources that don't have a `Spec` field such as ConfigMaps or Secrets.

**To Reproduce**

Deploy a `ManagedClusterAddOn` that has in its config a ConfigMap or Secret

**Expected behavior**

The framework should not discriminate these two resources and it should handle them properly

**Additional context**

Problem is with https://github.com/open-cluster-management-io/addon-framework/blob/71f1b13cbb6356279d5ae49667324ef5f9b7c3e0/pkg/utils/helpers.go#L354-L371

**Comment by haoqing0110** [comment]
Similar as https://github.com/open-cluster-management-io/ocm/issues/364, will fix it.

**Comment by qiujian16** [comment]
/close

this has been fixed
