### ISSUE TITLE
HealthChecker func when it returns an error, the statusCondition message doesn't include the error

### ISSUE THREAD

**Issue by tesshuflower** [open-cluster-management-io/addon-framework#295]
I'm using a healthchecker function, and when it returns an error, we get something like this in the status condition message:

```
Probe addon unavailable with err <nil>
```

Where we would expect to see the text from the error instead.

**Comment by tesshuflower** [comment]
I've created a proposed fix PR (#296), please let me know if you're ok with it!

**Comment by zhiweiyin318** [comment]
Thanks @tesshuflower . merged.
