### ISSUE TITLE
Suggesstions on README

### ISSUE THREAD

**Issue by ycyaoxdu** [open-cluster-management-io/addon-framework#56]
Hi, i'm a new learner. While following the README to get start with addon, i found some problems in [Deploy the helloworld addon](https://github.com/open-cluster-management-io/addon-framework#deploy-the-helloworld-addon).

1. the command `make image` needs to call `https://github.com/openshift/imagebuilder` to be installed & configured first.
this will be better:
```bash
$ go get github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.1
$ export PATH=$PATH:$(go env GOPATH)/bin
$ make images
```
2. the exported environment variable `EXAMPLE_IMAGE_NAME` is not used. 
kind load command can be modified:
```bash
kind load docker-image  $EXAMPLE_IMAGE_NAME --name <your-kind-cluster-name> # kind load docker-image  $EXAMPLE_IMAGE_NAME --name cluster1
```

**Comment by qiujian16** [comment]
thanks, would you like to send a PR to fix it :)

**Comment by ycyaoxdu** [comment]
ok，i will do this asap
