### ISSUE TITLE
Use manifestwork status to update addon status

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/addon-framework#74]
Some agent use lease to maintain the status of managedclusteraddon. We should have an approach in addon-framework that let addon-controller to update available status of managedclusteraddon. It could be based on:

1. feedback status from manifestwork
2. other customized way.

**Comment by qiujian16** [comment]
/kind feature

cc @yue9944882

**Comment by yue9944882** [comment]
> feedback status from manifestwork

@qiujian16 mmm the idea is intriguing. i was planning to add work-based addon healthiness previously, but it's merely mapping the overall success of the work object to the healthiness of the addon. a finer-grained mapping will be def more helpful, we can start by converging their coding interface in the framework.

**Comment by tesshuflower** [comment]
This feature would be very helpful for me, as I'm developing an addon controller that will not install an agent on managed clusters.

**Comment by qiujian16** [comment]
this is done

/close
