### ISSUE TITLE
Support change `installNamespace` of agent addons.

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/addon-framework#92]
Currently, the agent addon is installed in ns `open-cluster-management-agent-addon` by default.  

If a user is using the `WithInstallStrategy` function, then the installNamespace is unchangeable.

Could we provide a way to support user change installNamespace of agent addon in running time?

**Comment by qiujian16** [comment]
this is fixed in framework. The framework only create the addon if it does not exist now.

/close
